name: Updater

on:
  schedule:
    - cron: '33 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          git clone --bare https://github.com/ohmyzsh/ohmyzsh.git --single-branch --branch master
          cd ohmyzsh.git
          echo "Clone successful - Starting push"
          git push --mirror https://litetex:${{ secrets.CB_TOKEN }}@codeberg.org/litetex/ohmyzsh.git
          echo "Done"
