name: Updater

on:
  schedule:
    - cron: '33 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - source: ohmyzsh/ohmyzsh
            target: ohmyzsh
          - source: testflows/testflows-github-hetzner-runners
            target: testflows-github-hetzner-runners
          - source: openphish/public_feed
            target: openphish-public_feed
          - source: disposable-email-domains/disposable-email-domains
            target: disposable-email-domains
    steps:
      - run: |
          git clone --bare https://github.com/${{ matrix.source }}.git --single-branch
          source="${{ matrix.source }}"
          path_to_go=$(echo "${source##*/}")
          cd $path_to_go.git
          echo "Clone successful - Starting push"
          git push --mirror https://litetex:${{ secrets.CB_TOKEN }}@codeberg.org/litetex/${{ matrix.target }}.git
          echo "Done"
